{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "artifactory-ingest.serviceAccountName" . }}
  labels:
{{ include "artifactory-ingest.labels" . | indent 4 }}
{{- end -}}
